/* eslint-disable import/prefer-default-export */

export const minItems = [
  {
    id: '5ed1112909f2ff2d85b2c21b',
    basePrice: 3835.16,
    category: 3,
    deleted: true,
    description: 'Sint elit dolore pariatur in occaecat pariatur amet est officia elit ea enim. Enim amet enim elit ut nulla sit in minim eu ea. Consequat duis anim laboris laborum officia exercitation amet reprehenderit deserunt consequat fugiat ea aute ex. Ex deserunt labore in sunt ex proident sit ad. Ad elit excepteur irure eiusmod nisi Lorem eu qui ipsum ea. Ipsum excepteur non et velit occaecat duis ut.\r\n',
    name: 'fugiat',
    visible: true,
  },
  {
    id: '5ed111295a728d32a9ca49b7',
    basePrice: 1684.05,
    category: 2,
    deleted: false,
    description: 'Velit cillum veniam proident in deserunt voluptate cillum. Exercitation velit cillum id commodo aliquip dolor reprehenderit dolore consectetur. Non dolor do cillum nisi. Exercitation sint consectetur irure culpa laboris Lorem reprehenderit sit occaecat occaecat do aute esse. Irure minim nostrud sint adipisicing ipsum eu aliquip.\r\n',
    name: 'dolor',
    visible: true,
  },
  {
    id: '5ed1112908cf459fc5101684',
    basePrice: 1921.53,
    category: 0,
    deleted: true,
    description: 'Quis commodo occaecat ut in ad quis. Anim eiusmod dolore Lorem sunt eu sint adipisicing officia. Officia laboris ad dolor esse aliqua.\r\n',
    name: 'laborum',
    visible: false,
  },
  {
    id: '5ed111296d4090b28f206d38',
    basePrice: 3172.05,
    category: 2,
    deleted: false,
    description: 'Id fugiat consectetur proident nisi sunt quis sint duis minim adipisicing duis. Do enim amet do sit adipisicing elit qui consectetur. Elit laborum ullamco amet eu magna pariatur labore ad ea adipisicing ullamco. Cillum non aliqua aliqua ullamco voluptate voluptate ipsum nulla officia sunt. Excepteur velit aliquip ipsum pariatur laborum qui aliqua sunt. Ullamco pariatur consectetur amet dolor sit.\r\n',
    name: 'ipsum',
    visible: true,
  },
  {
    id: '5ed11129a3c7710259fa19e1',
    basePrice: 4388.14,
    category: 2,
    deleted: false,
    description: 'Est cupidatat est adipisicing est enim magna sit duis ad culpa Lorem labore. Nulla commodo laboris ut excepteur labore do ipsum sit proident officia. Elit esse non in minim in. Laboris laboris dolore tempor mollit consequat culpa id amet. Aliquip commodo cupidatat duis ad ut ex cupidatat in et sunt officia.\r\n',
    name: 'officia',
    visible: false,
  },
  {
    id: '5ed11129fb522bfdb34ebe21',
    basePrice: 3317.43,
    category: 3,
    deleted: false,
    description: 'Lorem veniam tempor est fugiat proident sit irure nisi veniam nostrud. Dolor id fugiat laboris elit cupidatat aute ad labore eu fugiat. Enim voluptate irure id minim amet anim occaecat officia sint pariatur laboris velit non consectetur. Pariatur est mollit sunt id laboris mollit adipisicing voluptate culpa eiusmod magna nisi. Pariatur dolore labore magna enim aute qui velit officia adipisicing sit ad. Laboris dolor nisi adipisicing veniam est veniam duis labore id ipsum dolor eiusmod. Est amet ex ex adipisicing in amet sit anim magna aliqua.\r\n',
    name: 'mollit',
    visible: false,
  },
  {
    id: '5ed11129f38a4da11e536dec',
    basePrice: 3623.22,
    category: 3,
    deleted: false,
    description: 'Cillum nulla nulla commodo sint laborum aliquip irure proident mollit dolore nostrud laboris irure. In mollit tempor fugiat aute nisi pariatur labore nostrud eiusmod duis. Laborum aute laborum do sit duis est excepteur sit Lorem eu dolor pariatur. In ea deserunt amet do adipisicing. Exercitation officia irure labore commodo voluptate adipisicing sit nisi consectetur occaecat non magna nisi. Fugiat qui ipsum nulla nisi eu et dolor tempor proident cupidatat proident ipsum cillum culpa.\r\n',
    name: 'mollit',
    visible: false,
  },
  {
    id: '5ed11129bf7508bf980aaebc',
    basePrice: 3488.74,
    category: 2,
    deleted: true,
    description: 'Sit exercitation ullamco anim mollit dolor nulla ut nisi occaecat in. Occaecat ut qui culpa qui laboris sunt. Consequat proident et eiusmod magna. Ullamco occaecat voluptate qui id nulla minim non velit commodo. Nostrud enim sunt sint magna ullamco officia reprehenderit non cupidatat minim elit. Aliqua adipisicing ex nostrud aute eu do ullamco. Excepteur pariatur nisi qui occaecat nisi veniam in.\r\n',
    name: 'eiusmod',
    visible: true,
  },
  {
    id: '5ed11129636830919c3d2175',
    basePrice: 2480.81,
    category: 0,
    deleted: false,
    description: 'Irure veniam magna labore nisi aliquip reprehenderit aliquip. Reprehenderit ex eu nisi esse id commodo nisi exercitation sunt dolor ad officia consectetur. Dolor laboris occaecat Lorem et id cillum dolor occaecat nisi.\r\n',
    name: 'nulla',
    visible: false,
  },
  {
    id: '5ed111295cc737557bf875ce',
    basePrice: 2468.8,
    category: 3,
    deleted: false,
    description: 'Irure eiusmod officia cupidatat veniam. Exercitation anim laborum cupidatat tempor irure do. Ut ad sunt id nostrud eiusmod mollit mollit. Officia sint eu id exercitation nisi consequat id dolore.\r\n',
    name: 'excepteur',
    visible: true,
  },
];

export const sellerStore = {
  categories: [
    {
      name: 'category 0',
    },
    {
      name: 'category 1',
    },
    {
      name: 'category 2',
    },
    {
      name: 'category 3',
    },
    {
      name: 'category 4',
    },
  ],
  currency: 'USD',
  email: 'hendersonreed@orbiflex.com',
  enableChatbot: true,
  enableInventoryManagement: false,
  enableRating: true,
  verified: false,
  storeName: 'ut qui',
  storeCustomization: {},
};
