export const AUTH_ACTION_TYPES = {
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_ERROR : 'LOGIN_ERROR',
    SIGNOUT_SUCCESS : 'SIGNOUT_SUCCESS',
    SIGNOUT_ERROR : 'SIGNOUT_ERROR',
}

export const CART_ACTION_TYPES = {
    DELETE_IN_PROGRESS : 'DELETE_IN_PROGRESS',
    DELETE_SUCCESS : 'DELETE_SUCCESS',
    DELETE_ERROR : 'DELETE_ERROR',
    EDIT_IN_PROGRESS : 'EDIT_IN_PROGRESS',
    EDIT_SUCCESS : 'EDIT_SUCCESS',
    EDIT_ERROR : 'EDIT_ERROR',
}

